### ISSUE TITLE
Wrong specular highlight

### ISSUE THREAD

**Issue by RioAraki** [alecjacobson/computer-graphics-shader-pipeline#24]
![2018-11-10-184916_636x363_scrot](https://user-images.githubusercontent.com/19270277/48307379-74b8a080-e519-11e8-8d83-059209503a64.png)

Hey, I tried to implement the blinn phong model and see the following effect. The highlight (spectacular light) looks really rough and different from the example showed. I remembered that in Alec's class, one example (twisted pipe) is showed about this issue: The prof had similar wrong highlight, and after the prof **did something,** the highlight is being corrected and looks really smooth. 

However, I forgot what the professor actually did. According to my rough memory the prof cut several lines of code from one section (vertex shader?) to another section (fragment shader?) and it turns to be right.

May the professor or anyone who remembered say again about what is being done to correct the highlight?

**Comment by ptanugra** [comment]
What happened was (as I recall), the professor had the shading calculated in the vertex shader and in the fragment shader part of the code it was simply assigning the color part. This results in the color getting interpolated weirdly* as it is passed on to the next step which is Rasterization.Recall the graphics pipeline (... -> Vertex Shader -> Rasterization -> Fragment Shader -> ...) . 

The fix was simple, all the professor did was simply pass the vertices in the vertex shader and then calculate the color in the fragment shader. This way, you are directly setting the color value with the blinn phong model!

**Comment by ptanugra** [comment]
btw, I have over simplified the graphics pipeline. Here is a more detailed one used by Vulkan.

![screen shot 2018-11-10 at 7 30 37 pm](https://user-images.githubusercontent.com/43912335/48307647-3f16b600-e51f-11e8-94df-8f349c21d90e.png)

**Comment by Panmani** [comment]
But the test-05.json file uses pass-through.vs. I guess we have to go with the "ulgier" specular highlight?

**Comment by RioAraki** [comment]
To answer my own question, it seems like my problem has nothing to do with what I am worried about. I forgot to perform inverse transpose of the model matrix (see lecture6 p21/46). Also, remember to normalize n, v, l in blinn phong

**Comment by ptanugra** [comment]
Yeah for this lab we are not supposed to touch with the vertex shader. All the coloring is done in the fragment shader. The professor at that time is just displaying what the graphic pipeline is doing "Behind the Scenes". 
Goodluck!

**Comment by WilsonWangTHU** [comment]
@RioAraki  i guess i own you a thank-you on that. Exact same bug here. thanks again ;p
